Completed prep-html-skeleton exercise -Andrew Owyang
Ajowyang/javascript-prep-0624-code-solutions pull request #2
Opened 2024-06-15 18:57 UTC by Ajowyang

<img width="1016" alt="Screenshot 2024-06-15 at 11 53 08 AM" src="https://github.com/Ajowyang/javascript-prep-0624-code-solutions/assets/36319661/58d454c3-0ae2-4807-bb02-47192b003175">

2024-06-15 18:58 UTC, shawnkost requested changes
Code looks good Andrew! We are just missing the quiz questions

2024-06-15 18:58 UTC, shawnkost commented on prep-html-skeleton/prep-html-skeleton-exercise-quiz-notes.md
> +
Don't forget about the quiz questions! You will need to answer these before submitting your work

2024-06-15 19:12 UTC, Ajowyang commented
I added the answers to the quiz questions on the md file, pushed it, and created another pull request. Is this what I'm supposed to do when you ask me to make more changes after my initial pull request?

2024-06-17 16:16 UTC, shawnkost approved these changes
👍🏻

2024-06-19 03:32 UTC, merged